### ISSUE TITLE
License not recognized

### ISSUE THREAD

**Issue by rotleaf** [Kaizen2977/Burp-Loader-Linux#1]
the key entered was not recognized and so it cant be cracked

**Comment by Kaizen2977** [comment]
in part 2 execution

open 1st terminal give this command
java --illegal-access=permit -Dfile.encoding=utf-8 -javaagent:/home/kali/Desktop/burp/loader.jar -noverify -jar /home/kali/Desktop/burp/burpsuite_pro_v2022.8.5.jar

OR

java -Dfile.encoding=utf-8 -javaagent:/home/kali/Desktop/burp/loader.jar -noverify -jar /home/kali/Desktop/burp/burpsuite_pro_v2022.8.5.jar


open 2nd terminal give this command
java -jar keygen.jar

make sure don't change the license name in keygen and  directory paths are right.
